CREATE TABLE petcare.tb_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    phone varchar(20),
    nickname varchar(50),
    avatar varchar(500),
    enabled smallint NOT NULL DEFAULT 1,
    address varchar(200),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_pet (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    name varchar(50) NOT NULL,
    type varchar(20),
    breed varchar(50),
    gender varchar(20),
    birthday date,
    weight numeric(5, 2),
    avatar varchar(500),
    health_notes varchar(500),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_health_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    record_type varchar(20) NOT NULL,
    title varchar(200),
    description text,
    record_time timestamp without time zone NOT NULL,
    value numeric(10, 2),
    symptom varchar(500),
    medication_info varchar(500),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_reminder (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    source_type varchar(20) NOT NULL,
    source_id bigint,
    title varchar(200),
    description text,
    record_time timestamp without time zone NOT NULL,
    schedule_time timestamp without time zone,
    remind_before_minutes integer NOT NULL DEFAULT 0,
    repeat_type varchar(20) NOT NULL DEFAULT 'NONE',
    repeat_config jsonb,
    is_active boolean NOT NULL DEFAULT true,
    total_occurrences integer NOT NULL DEFAULT 0,
    completed_count integer NOT NULL DEFAULT 0,
    completed_time timestamp without time zone,
    next_trigger_time timestamp without time zone,
    reminder_execution_id bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_reminder_execution (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_id bigint NOT NULL,
    pet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    schedule_time timestamp without time zone NOT NULL,
    actual_time timestamp without time zone,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    completion_notes text,
    notification_time timestamp without time zone NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    is_sent boolean NOT NULL DEFAULT false,
    sent_at timestamp without time zone,
    read_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_post (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    title varchar(200),
    content text,
    post_type varchar(16) NOT NULL,
    media_urls jsonb,
    external_link varchar(500),
    location_address varchar(500),
    price_range varchar(50),
    like_count integer NOT NULL DEFAULT 0,
    rating_count integer NOT NULL DEFAULT 0,
    rating_total integer NOT NULL DEFAULT 0,
    rating_avg numeric(3, 2) NOT NULL DEFAULT 0,
    view_count integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    audit_status varchar(20) NOT NULL DEFAULT 'PENDING',
    activity_id bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_label (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    type varchar(16) NOT NULL DEFAULT 'GENERAL',
    icon varchar(200),
    color varchar(20),
    use_count integer NOT NULL DEFAULT 0,
    is_recommended smallint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_post_label (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL,
    label_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE petcare.tb_interaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL,
    interaction_type varchar(16) NOT NULL,
    rating_value smallint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE petcare.tb_activity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    title varchar(200) NOT NULL,
    description text,
    cover_image varchar(500),
    activity_type varchar(16) NOT NULL,
    activity_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    address varchar(500),
    online_link varchar(500),
    max_participants integer NOT NULL DEFAULT 0,
    current_participants integer NOT NULL DEFAULT 0,
    status varchar(16) NOT NULL DEFAULT 'RECRUITING',
    audit_status varchar(20) NOT NULL DEFAULT 'PENDING',
    labels jsonb,
    check_in_enabled smallint NOT NULL DEFAULT 1,
    check_in_count integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_knowledge_document (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    file_url varchar(500) NOT NULL,
    file_type varchar(20) NOT NULL,
    file_size bigint NOT NULL,
    version integer NOT NULL DEFAULT 1,
    status smallint NOT NULL DEFAULT 1,
    chunk_count integer NOT NULL DEFAULT 0,
    processing_status varchar(20) NOT NULL DEFAULT 'PENDING',
    processing_error varchar(500),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_points_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    available_points integer NOT NULL DEFAULT 0,
    total_points integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_points_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    points integer NOT NULL,
    points_before integer NOT NULL,
    points_after integer NOT NULL,
    action_type varchar(32) NOT NULL,
    biz_type varchar(32),
    biz_id bigint,
    coupon_id bigint,
    coupon_deduct integer,
    remark varchar(255),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE petcare.tb_points_coupon_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    face_value integer NOT NULL,
    valid_days integer NOT NULL,
    total_count integer NOT NULL DEFAULT 0,
    issued_count integer NOT NULL DEFAULT 0,
    per_user_limit integer NOT NULL DEFAULT 1,
    source_type varchar(16) NOT NULL DEFAULT 'SYSTEM',
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_points_coupon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    template_id bigint NOT NULL,
    face_value integer NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'UNUSED',
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    used_time timestamp without time zone,
    used_record_id bigint,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code varchar(50) NOT NULL,
    role_name varchar(100) NOT NULL,
    description varchar(500),
    sort integer NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp without time zone
);

CREATE TABLE petcare.tb_user_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
